baseURL = "https://gosyuliya.github.io/docs_cif/"
title = "Документация Платформы Цифриума"
theme = "shadocs"
enableGitInfo = true # Доступ к репозиторию
defaultContentLanguage = "ru"
[languages]
  [languages.ru]
    languageName = "Русский"
    contentDir = "content/ru"
    [languages.ru.params]
      timeFormat = "02 января 2006"

[params]
  siteContentOrder         = "weight" # Сортировка
  enableRightSidebar       = true  # Включение правой боковой панели
  enableTOC                = true  # Включение дерева навигации (оглавления)
  enableSearch             = false  
  currentVersion           = "latest"  # Curent version of the website
  latestVersionUrl         = "https://gosyuliya.github.io/docs_cif/"  # Url of the latest version of the website
  navbarInfo               = false
  #globalBanner            = true
  search                   = true
  relativeURLs             = true

[outputs]
  home = ["HTML", "JSON"]
    
[params.includes]
    css = ["css/custom.css"]
